name: Test Maven Toolchains Setup (No Manual JAVA_HOME)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 11 and 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: |
            11
            17

      - name: Verify Java version for Maven command
        run: java -version

      - name: Build with Maven
        run: mvn -B package --file pom.xml
