name: Test Maven Toolchains Setup (No Manual JAVA_HOME)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17 and 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: |
            17
            11
      # - name: Set JAVA_HOME and update PATH to JDK 17 for Maven
      #   run: |
      #     echo "JAVA_HOME=${JAVA_HOME_17_X64}" >> $GITHUB_ENV
      #     echo "${JAVA_HOME_17_X64}/bin" >> $GITHUB_PATH
      
      # Set JAVA_HOME and update PATH to use JDK 17
      - name: Set JAVA_HOME to JDK 17
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
        run: |
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Verify Java version for Maven command
        run: java -version

      - name: Build with Maven
        run: mvn --batch-mode verify
