name: Test Maven Toolchains Setup (No Manual JAVA_HOME)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17 and 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: |
            17
            11

      - name: Verify Java version for Maven command
        run: java -version

      - name: Build with Maven with JDK 17
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
          PATH: ${{ env.JAVA_HOME_17_X64 }}/bin:${{ env.PATH }}
        run: |
          echo $PATH
          mvn --batch-mode verify
